Default: &defaults
  database: goodLuckJim.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: goodLuckJim_test.sqlite3
  <<: *defaults

Staging:
  database: goodLuckJim_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: goodLuckJim_production.sqlite3
  poolsize: 100
  <<: *defaults
